// 20211SVAC/G05/TytusDS/src/app/PaginasWeb/seleccion/seleccion.component.ts
import { Component, OnInit } from '@angular/core';
import { OrdenamientoSeleccion } from './ts/seleccion';
import { DocumentoService } from '../../services/documento.service';
import { Chart } from 'node_modules/chart.js';
import { saveAs } from 'file-saver';

@Component({
  selector: 'app-seleccion',
  templateUrl: './seleccion.component.html',
  styleUrls: ['./seleccion.component.css']
})
export class SeleccionComponent implements OnInit {

  orden: OrdenamientoSeleccion;
  arreglo: any = [];
  iteraciones: any = [];
  tiempo = 3000;
  index = 0;
  cadena = false;

  constructor(private documentoService: DocumentoService) {
    this.orden = new OrdenamientoSeleccion();
  }

  ngOnInit(): void {}

  getOpciones(opciones: any): void {
    this.tiempo = opciones['velocidadOrdenamientos'];
  }

  graficar(): void {
    if (this.iteraciones[this.index] === undefined) {
      return;
    }
    let datos = this.iteraciones[this.index];
    if (this.cadena) {
      datos = [];
      this.iteraciones[0].forEach(element => {
        datos.push(10);
      });
    }
    let colores: string[] = [];
    this.iteraciones[this.index].forEach( ite => {
      colores.push(`rgba(${Math.floor(Math.random() * 250)},${Math.floor(Math.random() * 250)},${Math.floor(Math.random() * 250)}, 1)`);
    });
    var myChart = new Chart('myChart', {
      type: 'bar',
      data: {
          labels: this.iteraciones[this.index],
          datasets: [{
              label: 'Ordenamiento de Seleccion',
              data: datos,
              backgroundColor: colores,
              borderColor: colores,
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              y: {
                  beginAtZero: true
              }
          }
      }
    });
    this.index += 1;
    setTimeout(() => {
      this.graficar();
    }, this.tiempo);
    
  }

  getDocumento(documento: any): void {
    this.iteraciones = [];
    this.arreglo = [];
    this.cadena = false;
    this.documentoService.getDocumento(documento).then( contenido => {
      //this.arreglo = this.orden.ordenar(contenido['valores'], contenido['cuenta']);
      this.arreglo = this.orden._ordenar(contenido['valores']);
      console.log(this.arreglo);
      this.imprimirIteraciones();
    });
  }

  imprimirIteraciones(): void {
    if (isNaN(parseInt(this.arreglo[0][0]))){
      this.cadena = true;
      console.log('no es un numero');
      this.arreglo.forEach((arr: any) => {
        const nuevoArr = arr.split(',');
        this.iteraciones.push(nuevoArr);
      });
      this.graficar();
      return;
    }
    this.arreglo.forEach( (arr: any) => {
      const nuevoArr = arr.split(',');
      let final: number[] = [];
      nuevoArr.forEach( (valor: string) => {
        final.push(parseInt(valor, 10));
      });
      this.iteraciones.push(final);
    });
    this.graficar();
  }

  guardar(): void {
    if (this.iteraciones.length === 0){
      return;
    }
    const contenido: any = {
      categoria: "Ordenamiento",
      nombre: "De seleccion",
      valores: this.iteraciones[this.iteraciones.length - 1]
    };
    let blob = new Blob([JSON.stringify(contenido)], {type: 'json;charset=utf-8'});
    saveAs(blob, 'ordenamiento-seleccion.json');
  }

}

<div class="container mt-3" id="contenedor">
  <app-opciones (opcionesEvento)="getOpciones($event)"></app-opciones>
    <h1 class="fw-light text-white">Ordenamiento de Selección</h1>
    <hr>
    <div class="row my-3">
        <div class="col-md-6">
            <input class="form-control" type="file" id="formFile" (change)="getDocumento($event.target)">
        </div>
        <div class="col-md-5"></div>
        <div class="col-md-1">
            <div class="d-grid gap-2">
                <button class="btn btn-success" (click)="guardar()" [disabled]="iteraciones.length === 0">Guardar</button>
            </div>
        </div>
    </div>
    <div id="divChart" class="container" style="display: block;">
        <canvas class="bg-light mt-3" id="myChart" style="width: 100%; height: 500px;"></canvas>
    </div>
</div>

// 20211SVAC/G18/src/OrdenamientoComponentes/Seleccion.jsx
import React, { Component } from 'react'
import { Bar, defaults } from 'react-chartjs-2'
import "./seleccion.css"

export class Seleccion extends Component {
    constructor(props) {
        super(props)

        this.state = {
            valorSeleccion: "",
            seleccion: [],
            arregloPalabra: [],
            valoresAscci: [],
            arregloPalabraOrdenado: [],
            tamañoAscci: 0

        }
        this.leerJson = this.leerJson.bind(this)
    }


    handleChange = (e) => {
        // console.log({
        //     name: e.target.name,
        //     value: e.target.value

        // });

        this.setState({
            valorSeleccion: e.target.value
        })
    };



    handleSubmit = (e) => {
        e?.preventDefault();
       
        let numero = parseInt(this.state.valorSeleccion);
        let palabra = this.state.valorSeleccion;

        if (Number.isNaN(numero)) {

            this.state.arregloPalabra.push(palabra);

        } else {

            this.state.seleccion.push(numero);
        };

        this.setState({
            seleccion: this.state.seleccion
        })

        this.letrasAnumeros(this.state.arregloPalabra)
    };



    leerJson(event) {
        const input = event.target
        const reader = new FileReader()
        reader.onload = (event) => {
            const text = reader.result

            const json = JSON.parse(text)
            const valores = json.valores

            valores.forEach((element, index) => {
                setTimeout(() => {
                    this.setState({
                        valorSeleccion: element,
                    }, () => {
                        this.handleSubmit()
                    })

                }, index * 1000)
            });

            this.setState({
                data: json
            })
        }
        reader.readAsText(input.files[0], "UTF-8")
    }



     ordenamientoAnimacion = (contador, listaSeleccion, siesTexto) => {


         setTimeout(() => {
            this.setState({
                seleccion: siesTexto ? []:  listaSeleccion,
                arregloPalabraOrdenado: siesTexto ? listaSeleccion: []
            })
        },  contador*550)
    }

    sumaAscii = (cadena) => {

        for (let i = 0; i < cadena.length; i++) {

            this.state.tamañoAscci = this.state.tamañoAscci + parseInt(cadena.charCodeAt(i))
        }
    }

    letrasAnumeros = (arreglo) => {


     
        this.state.valoresAscci = []
        for (let i = 0; i < arreglo.length; i++) {
            let tmp = arreglo[i]
            this.sumaAscii(tmp)

            this.state.valoresAscci.push(this.state.tamañoAscci)
            this.state.tamañoAscci = 0

        }

        this.state.arregloPalabraOrdenado = []

        for (let x = 0; x < this.state.valoresAscci.length; x++) {

            this.state.arregloPalabraOrdenado.push(
                {
                    palabra: {
                        string: this.state.arregloPalabra[x],
                        tamañoAscci: this.state.valoresAscci[x]
                    }


                }
            )


        }

        this.setState({
            arregloPalabra: arreglo
        })
    }





    ordenamiento = () => {


        let valor  = parseInt(this.state.seleccion[0]);
        
        if(Number.isNaN(valor)){
            const listaSeleccion = this.state.arregloPalabraOrdenado
            const tamañoLista = this.state.arregloPalabraOrdenado.length
            let contador = 0

            for (let i = 0; i < tamañoLista; i++) {
                let minimo = i
                for (let j = i + 1; j < tamañoLista; j++) {
                    if (listaSeleccion[minimo]['palabra']['tamañoAscci'] > listaSeleccion[j]['palabra']['tamañoAscci']) {

                        minimo = j;
                       
         
                    }
                    this.ordenamientoAnimacion(++contador, [...listaSeleccion],true)
                }   
            
                if(minimo != i){
                    let temporal = listaSeleccion[i]
                    listaSeleccion[i] =  listaSeleccion[minimo]
                    listaSeleccion[minimo] = temporal
                    this.ordenamientoAnimacion(++contador, [...listaSeleccion],true)
                }
         
         
            }


        }else{
            const listaSeleccion = this.state.seleccion
            const tamañoLista = this.state.seleccion.length

            let contador = 0

            for (let i = 0; i < tamañoLista; i++) {
                let minimo = i
                
                for (let j = i + 1; j < tamañoLista; j++) {
                    if (listaSeleccion[minimo] > listaSeleccion[j]) {

                        minimo = j;
                        
         
                    }
                    this.ordenamientoAnimacion(++contador, [...listaSeleccion],false)
                }   
            
                if(minimo != i){
                    let temporal = listaSeleccion[i]
                    listaSeleccion[i] =  listaSeleccion[minimo]
                    listaSeleccion[minimo] = temporal
                    this.ordenamientoAnimacion(++contador, [...listaSeleccion],false)
                }
         
         
            }
        }


    }


    render() {
        console.log(this.state.seleccion)
        console.log(this.state.arregloPalabraOrdenado)
        return (
            <div>
                <form onSubmit={this.handleSubmit}>
                    <div className="container">

                        <div className="row gap-2">
                            <div className="col-sm-2 d-grid gap-2">
                                <input
                                    type="text"
                                    className="form-control"
                                    id="Elemento"
                                    placeholder="Elemento"
                                    onChange={this.handleChange}
                                    value={this.state.valorSeleccion}
                                />
                            </div>

                            <div className="col-sm-2 d-grid gap-2">
                                <button type="submit" className="btn btn-success" onClick={this.handleClick} >Agregar elemento</button>
                            </div>

                            <div className="col-sm-2 d-grid gap-2">
                                <button type="button" className="btn btn-success" onClick={this.ordenamiento} >Ordenar</button>
                            </div>
                            <div className="col-sm-2 d-grid gap-2"> 
                                <input type="file" class="form-control" onChange={this.leerJson} />    
                                </div>
                        </div>

                    </div>
                </form>

                <div className="container">
                    <div className="card mt-4">
                        <Bar
                            data={{
                                labels: this.state.seleccion.length > 0 ? this.state.seleccion : this.state.arregloPalabraOrdenado.map((palabra) => palabra.palabra.string),
                                options: {
                                    plugins: {
                                        legend: {
                                            labels: {
                                                // This more specific font property overrides the global property
                                                font: {
                                                    size: 200
                                                }
                                            }
                                        }
                                    }
                                },

                                datasets: [
                                    {
                                        label: 'ordenamiento de seleccion ',
                                        data:  this.state.seleccion.length > 0 ? this.state.seleccion : this.state.arregloPalabraOrdenado.map((palabra) => palabra.palabra.tamañoAscci),
                                        backgroundColor: [
                                            'rgba(255, 99, 132, 0.2)',
                                            'rgba(54, 162, 235, 0.2)',
                                            'rgba(255, 206, 86, 0.2)',
                                            'rgba(75, 192, 192, 0.2)',
                                            'rgba(153, 102, 255, 0.2)',
                                            'rgba(255, 159, 64, 0.2)',
                                        ],
                                        borderColor: [
                                            'rgba(255, 99, 132, 1)',
                                            'rgba(54, 162, 235, 1)',
                                            'rgba(255, 206, 86, 1)',
                                            'rgba(75, 192, 192, 1)',
                                            'rgba(153, 102, 255, 1)',
                                            'rgba(255, 159, 64, 1)',
                                        ],
                                        borderWidth: 1,
                                    },
                                    // {
                                    //   label: 'Quantity',
                                    //   data: [47, 52, 67, 58, 9, 50],
                                    //   backgroundColor: 'orange',
                                    //   borderColor: 'red',
                                    // },
                                ],
                            }}
                            height={400}
                            width={600}
                            options={{
                                maintainAspectRatio: false,
                                scales: {
                                    yAxes: [
                                        {
                                            ticks: {
                                                beginAtZero: true,
                                            },
                                        },
                                    ],
                                },
                                legend: {
                                    labels: {
                                        fontSize: 25,
                                    },
                                },
                            }}
                        />


                    </div>


                </div>

            </div>
        )
    }
}

export default Seleccion
